quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.hibernate-orm.database.generation=update
mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}
mp.jwt.verify.issuer=https://activity-planner.app
smallrye.jwt.sign.key=${JWT_PRIVATE_KEY}
app.refresh-token.expiration-days=30

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://activity.lucasvandepol.com
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=origin,content-type,accept,authorization
quarkus.http.cors.access-control-allow-credentials=true